package com.seruiso.radio1

data class MusicTvChannel(
    val name: String,
    val url: String,
    val country: String,
    val countryLabel: String,
    val logo: String? = null,
)

object MusicTvChannels {
    private const val B = "http://b468f60e.russtv.net/iptv/TP6ZE44WPGBCMSTYY526SQYT"
    val all: List<MusicTvChannel> = listOf(
        MusicTvChannel("НТН HD", "$B/15235/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Сфера ТВ HD", "$B/15011/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Kinogrande HD", "$B/15008/index.m3u8", "UA", "Україна"),
        MusicTvChannel("5 Канал", "$B/15007/index.m3u8", "UA", "Україна"),
        MusicTvChannel("24 Канал FHD", "$B/945/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Надія ТВ", "$B/951/index.m3u8", "UA", "Україна"),
        MusicTvChannel("EU Music HD", "$B/956/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Мега", "$B/925/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Мега HD", "$B/929/index.m3u8", "UA", "Україна"),
        MusicTvChannel("К2", "$B/15124/index.m3u8", "UA", "Україна"),
        MusicTvChannel("К2 HD", "$B/930/index.m3u8", "UA", "Україна"),
        MusicTvChannel("К1 HD", "$B/15126/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Новий Канал", "$B/15125/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Новий Канал HD", "$B/935/index.m3u8", "UA", "Україна"),
        MusicTvChannel("НТН", "$B/15128/index.m3u8", "UA", "Україна"),
        MusicTvChannel("4ever Music HD", "$B/936/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Тернопіль 1 HD", "$B/970/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший Міський HD (Одеса)", "$B/975/index.m3u8", "UA", "Україна"),
        MusicTvChannel("СК1", "$B/981/index.m3u8", "UA", "Україна"),
        MusicTvChannel("1+1 Україна FHD", "$B/982/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Star Cinema HD", "$B/987/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Чернівецький Промінь", "$B/992/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший", "$B/1004/index.m3u8", "UA", "Україна"),
        MusicTvChannel("5 Канал HD", "$B/1016/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Інтер HD", "$B/1030/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Рибалка FHD", "$B/1047/index.m3u8", "UA", "Україна"),
        MusicTvChannel("1+1 International", "$B/1058/index.m3u8", "UA", "Україна"),
        MusicTvChannel("2+2", "$B/994/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ТВА HD (Чернівці)", "$B/995/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Zoom", "$B/998/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Zoom HD", "$B/1000/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ПлюсПлюс", "$B/15130/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Eco TV HD", "$B/1002/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ТЕТ", "$B/1006/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Сонце", "$B/1009/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Прямий HD", "$B/1013/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Уніан Серіал HD", "$B/1015/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Київ", "$B/1023/index.m3u8", "UA", "Україна"),
        MusicTvChannel("8 Канал HD", "$B/1045/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ТВА (Чернівці)", "$B/1046/index.m3u8", "UA", "Україна"),
        MusicTvChannel("24 Канал HD", "$B/1072/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Тернопіль 1", "$B/1063/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ICTV HD", "$B/5041/index.m3u8", "UA", "Україна"),
        MusicTvChannel("СТБ", "$B/6302/index.m3u8", "UA", "Україна"),
        MusicTvChannel("СТБ HD", "$B/6304/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Інтер", "$B/15122/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Еспресо", "$B/6305/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Sport 1", "$B/6311/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Sport 2", "$B/6313/index.m3u8", "UA", "Україна"),
        MusicTvChannel("1+1 Марафон", "$B/6314/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Еспресо HD", "$B/6317/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Піксель TV HD", "$B/15127/index.m3u8", "UA", "Україна"),
        MusicTvChannel("8 Канал FHD", "$B/6327/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Бігуді", "$B/6330/index.m3u8", "UA", "Україна"),
        MusicTvChannel("NIKI Kids HD", "$B/6332/index.m3u8", "UA", "Україна"),
        MusicTvChannel("NIKI Junior HD", "$B/6333/index.m3u8", "UA", "Україна"),
        MusicTvChannel("М1 HD", "$B/6334/index.m3u8", "UA", "Україна"),
        MusicTvChannel("М2 HD", "$B/6335/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ICTV", "$B/6339/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Апостроф TV HD", "$B/6373/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Оце HD", "$B/6375/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший HD", "$B/6376/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ТЕТ HD", "$B/6377/index.m3u8", "UA", "Україна"),
        MusicTvChannel("2+2 HD", "$B/6378/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ПлюсПлюс HD", "$B/6379/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Оце", "$B/6380/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Еспресо FHD", "$B/9073/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший Автомобільний HD", "$B/7228/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Star Cinema FHD", "$B/15262/index.m3u8", "UA", "Україна"),
        MusicTvChannel("FilmBox+ One", "$B/15266/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Enter-фільм HD", "$B/15273/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Eco TV", "$B/15275/index.m3u8", "UA", "Україна"),
        MusicTvChannel("EU Music FHD", "$B/15277/index.m3u8", "UA", "Україна"),
        MusicTvChannel("4ever Music", "$B/15278/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Уніан Серіал", "$B/31726/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Фауна", "$B/31727/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Ми Україна", "$B/31731/index.m3u8", "UA", "Україна"),
        MusicTvChannel("НТА HD", "$B/31732/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Наука", "$B/31733/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Obozrevatel TV HD", "$B/31734/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший Міський HD (Кривий Ріг)", "$B/31736/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Рада HD", "$B/31739/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Рибалка HD", "$B/31743/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Суспільне Київ HD", "$B/31745/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Суспільне Крим HD", "$B/31746/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Суспільне Культура HD", "$B/31747/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Суспільне Спорт HD", "$B/31750/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Суспільне Спорт FHD", "$B/31751/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Перший Західний HD", "$B/31752/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Терра", "$B/31753/index.m3u8", "UA", "Україна"),
        MusicTvChannel("UTravel HD", "$B/31762/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Ісландія HD", "$B/31769/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Аверс", "$B/31770/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Армія TV HD", "$B/31771/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Галичина HD", "$B/31772/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Дача", "$B/31775/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Дім", "$B/31776/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Raz 3 HD", "$B/31780/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Київ HD", "$B/31781/index.m3u8", "UA", "Україна"),
        MusicTvChannel("1+1 Україна HD", "$B/31784/index.m3u8", "UA", "Україна"),
        MusicTvChannel("11 Канал HD (Дніпро)", "$B/31785/index.m3u8", "UA", "Україна"),
        MusicTvChannel("36.6 TV", "$B/31787/index.m3u8", "UA", "Україна"),
        MusicTvChannel("4ever Cinema HD", "$B/31788/index.m3u8", "UA", "Україна"),
        MusicTvChannel("6 Соток", "$B/31790/index.m3u8", "UA", "Україна"),
        MusicTvChannel("AMC", "$B/31792/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Bolt HD", "$B/31793/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Cine+ HD", "$B/31794/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Cine+ Hit HD", "$B/31795/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Cine+ Kids HD", "$B/31796/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Cine+ Legend HD", "$B/31797/index.m3u8", "UA", "Україна"),
        MusicTvChannel("D1 HD", "$B/31798/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Da Vinci HD", "$B/31799/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Divi Sport HD", "$B/31800/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Equalympic HD", "$B/31802/index.m3u8", "UA", "Україна"),
        MusicTvChannel("FilmUA Drama", "$B/31805/index.m3u8", "UA", "Україна"),
        MusicTvChannel("FilmBox+ Festival", "$B/31807/index.m3u8", "UA", "Україна"),
        MusicTvChannel("FilmUA Live HD", "$B/31808/index.m3u8", "UA", "Україна"),
        MusicTvChannel("FreeДом", "$B/31810/index.m3u8", "UA", "Україна"),
        MusicTvChannel("К1", "$B/31812/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Kino Action HD", "$B/31813/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Kino Comedy HD", "$B/31814/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Kino Premiere HD", "$B/31815/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Kinosweet HD", "$B/31816/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Твій Серіал HD", "$B/32115/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Super+ HD", "$B/32116/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Твоє Кіно Action HD", "$B/32117/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Твоє Кіно Relax HD", "$B/32118/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Твоє Кіно Хіт HD", "$B/32119/index.m3u8", "UA", "Україна"),
        MusicTvChannel("ATR HD", "$B/32120/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Кус-Кус", "$B/32121/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Кус-Кус HD", "$B/32122/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Бігуді HD", "$B/32123/index.m3u8", "UA", "Україна"),
        MusicTvChannel("InRating TV HD", "$B/16020/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Deluxe Dance HD", "$B/31558/index.m3u8", "DE", "Німеччина"),
        MusicTvChannel("Deluxe Music HD", "$B/17047/index.m3u8", "DE", "Німеччина"),
        MusicTvChannel("Dance TV · EDM", "$B/2395/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("MTV HD US", "$B/2130/index.m3u8", "US", "США"),
        MusicTvChannel("MTV US", "$B/19192/index.m3u8", "US", "США"),
        MusicTvChannel("MTV Classic", "$B/19148/index.m3u8", "US", "США"),
        MusicTvChannel("Deejay TV HD", "$B/10070/index.m3u8", "IT", "Італія"),
        MusicTvChannel("Kiss Kiss HD", "$B/16072/index.m3u8", "IT", "Італія"),
        MusicTvChannel("Kiss Kiss Italia HD", "$B/16073/index.m3u8", "IT", "Італія"),
        MusicTvChannel("NRG 91 HD", "$B/7223/index.m3u8", "GR", "Греція"),
        MusicTvChannel("Baraza Music HD", "$B/10077/index.m3u8", "GR", "Греція"),
        MusicTvChannel("KroneHit TV HD", "$B/10065/index.m3u8", "AT", "Австрія"),
        MusicTvChannel("V2BEAT HD", "$B/15020/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's 80s", "$B/17057/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's 70s", "$B/19194/index.m3u8", "UK", "Британія"),
        MusicTvChannel("Now 80s", "$B/19196/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's Rock", "$B/19197/index.m3u8", "UK", "Британія"),
        MusicTvChannel("RFM TV HD", "$B/1038/index.m3u8", "FR", "Франція"),
        MusicTvChannel("NRJ Hits HD", "$B/19199/index.m3u8", "FR", "Франція"),
        MusicTvChannel("Retro Music TV", "$B/31554/index.m3u8", "CZ", "Чехія"),
        MusicTvChannel("1HD Music Television", "$B/17038/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("FRESH Dance HD", "$B/18087/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("FRESH Hits HD", "$B/18084/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Trace Urban HD", "$B/15107/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Mezzo Live HD", "$B/208/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Mezzo", "$B/707/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Classic Music", "$B/14008/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Classic Music HD", "$B/14009/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Spirit TV HD", "$B/10073/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Yosso TV Music Hits", "$B/14179/index.m3u8", "INT", "Міжнародні"),
    )

    val sections: List<Pair<String, String>> = listOf(
        "UA" to "Україна",
        "WORLD" to "Музика світу",
    )

    fun bySection(code: String): List<MusicTvChannel> = when (code) {
        "UA" -> all.filter { it.country == "UA" }
        "WORLD" -> all.filter { it.country != "UA" }
        else -> emptyList()
    }

    fun byCountry(code: String): List<MusicTvChannel> = bySection(code)
}
