package com.seruiso.radio1

data class MusicTvChannel(
    val name: String,
    val url: String,
    val country: String,
    val countryLabel: String,
    val logo: String? = null,
)

object MusicTvChannels {
    private const val B = "http://b468f60e.russtv.net/iptv/TP6ZE44WPGBCMSTYY526SQYT"
    val all: List<MusicTvChannel> = listOf(
        MusicTvChannel("InRating TV HD", "$B/16020/index.m3u8", "UA", "Україна"),
        MusicTvChannel("Deluxe Dance HD", "$B/31558/index.m3u8", "DE", "Німеччина"),
        MusicTvChannel("Deluxe Music HD", "$B/17047/index.m3u8", "DE", "Німеччина"),
        MusicTvChannel("Deluxe Music HD orig", "$B/14148/index.m3u8", "DE", "Німеччина"),
        MusicTvChannel("MTV HD US", "$B/2130/index.m3u8", "US", "США"),
        MusicTvChannel("MTV US", "$B/19192/index.m3u8", "US", "США"),
        MusicTvChannel("MTV Classic", "$B/19148/index.m3u8", "US", "США"),
        MusicTvChannel("Deejay TV HD", "$B/10070/index.m3u8", "IT", "Італія"),
        MusicTvChannel("Kiss Kiss HD", "$B/16072/index.m3u8", "IT", "Італія"),
        MusicTvChannel("Kiss Kiss Italia HD", "$B/16073/index.m3u8", "IT", "Італія"),
        MusicTvChannel("Zerouno TV HD", "$B/16076/index.m3u8", "IT", "Італія"),
        MusicTvChannel("NRG 91 HD", "$B/7223/index.m3u8", "GR", "Греція"),
        MusicTvChannel("Baraza Music HD", "$B/10077/index.m3u8", "GR", "Греція"),
        MusicTvChannel("KroneHit TV HD", "$B/10065/index.m3u8", "AT", "Австрія"),
        MusicTvChannel("V2BEAT HD", "$B/15020/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's 80s", "$B/17057/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's 70s", "$B/19194/index.m3u8", "UK", "Британія"),
        MusicTvChannel("Now 80s", "$B/19196/index.m3u8", "UK", "Британія"),
        MusicTvChannel("That's Rock", "$B/19197/index.m3u8", "UK", "Британія"),
        MusicTvChannel("RFM TV HD", "$B/1038/index.m3u8", "FR", "Франція"),
        MusicTvChannel("NRJ Hits HD", "$B/19199/index.m3u8", "FR", "Франція"),
        MusicTvChannel("Retro Music TV", "$B/31554/index.m3u8", "CZ", "Чехія"),
        MusicTvChannel("Перший музичний HD BY", "$B/14144/index.m3u8", "BY", "Білорусь"),
        MusicTvChannel("Перший музичний BY", "$B/14145/index.m3u8", "BY", "Білорусь"),
        MusicTvChannel("Dance TV · EDM", "$B/2395/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("1HD Music Television", "$B/17038/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("1HD Music Television orig", "$B/9001/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Mezzo Live HD", "$B/208/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Mezzo", "$B/707/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("iConcerts HD", "$B/9056/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Trace Urban HD", "$B/15107/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Spirit TV HD", "$B/10073/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("MM Relax HD", "$B/13030/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Classic Music", "$B/14008/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Classic Music HD", "$B/14009/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Yosso TV Music Hits", "$B/14179/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Bridge Deluxe HD", "$B/236/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Deluxe HD orig", "$B/9012/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Hits", "$B/711/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Hits HD", "$B/19227/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge TV", "$B/122/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge TV orig", "$B/9253/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Rock", "$B/17043/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Rock HD", "$B/19225/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Русский Хит", "$B/120/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Русский Хит HD", "$B/19226/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Русский Хит orig", "$B/9176/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Classic", "$B/32113/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Classic orig", "$B/9259/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Шлягер", "$B/10038/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Bridge Фрэш", "$B/17045/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Europa Plus TV HD", "$B/20029/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Europa Plus TV", "$B/115/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Europa Plus TV orig", "$B/9257/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МУЗ-ТВ", "$B/116/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МУЗ-ТВ orig", "$B/9169/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МУЗ-ТВ +0", "$B/15461/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МУЗ-ТВ +3", "$B/15441/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МУЗ-ТВ +4", "$B/6036/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Музыка Первого", "$B/155/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Музыка Первого orig", "$B/9166/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Жара HD", "$B/2129/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Жара", "$B/105/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Жара orig", "$B/9177/index.m3u8", "RU", "Росія"),
        MusicTvChannel("РУ.ТВ", "$B/838/index.m3u8", "RU", "Росія"),
        MusicTvChannel("РУ.ТВ HD", "$B/19247/index.m3u8", "RU", "Росія"),
        MusicTvChannel("РУ.ТВ orig", "$B/32233/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Шансон ТВ", "$B/859/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Шансон ТВ orig", "$B/9173/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Music Box Russia", "$B/2048/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Music Box Russia HD", "$B/19255/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Music Box Russia orig", "$B/9168/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Music Box Gold", "$B/14149/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Музыка Live", "$B/2043/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Музыка Live orig", "$B/9174/index.m3u8", "RU", "Росія"),
        MusicTvChannel("MCM Top Russia", "$B/836/index.m3u8", "RU", "Росія"),
        MusicTvChannel("MCM Top Russia orig", "$B/9175/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FON Music", "$B/710/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FON Music HD", "$B/19223/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FON Music orig", "$B/9178/index.m3u8", "RU", "Росія"),
        MusicTvChannel("о2тв HD", "$B/2141/index.m3u8", "RU", "Росія"),
        MusicTvChannel("о2тв", "$B/2068/index.m3u8", "RU", "Росія"),
        MusicTvChannel("о2тв HD orig", "$B/9254/index.m3u8", "RU", "Росія"),
        MusicTvChannel("о2тв orig", "$B/9256/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МузСоюз HD", "$B/2137/index.m3u8", "RU", "Росія"),
        MusicTvChannel("МузСоюз orig", "$B/9171/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Жар Птица", "$B/2142/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Жар Птица orig", "$B/9165/index.m3u8", "RU", "Росія"),
        MusicTvChannel("AIVA TV HD", "$B/2156/index.m3u8", "RU", "Росія"),
        MusicTvChannel("AIVA TV HD orig", "$B/9085/index.m3u8", "RU", "Росія"),
        MusicTvChannel("SONGTV Россия HD", "$B/6394/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Курай ТВ HD", "$B/2144/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Курай ТВ", "$B/2061/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Курай ТВ HD orig", "$B/9255/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Курай ТВ orig", "$B/9252/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Vostok TV", "$B/1054/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Страна ТВ HD", "$B/14152/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Перший музичний HD", "$B/14142/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Перший музичний", "$B/14143/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Z!Music HD", "$B/14138/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Z!Rock HD", "$B/14139/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Hits HD", "$B/18084/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Russian Hits HD", "$B/18085/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Sad Music HD", "$B/18086/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Dance HD", "$B/18087/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Rock HD", "$B/18088/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Rock Covers HD", "$B/18089/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Russian Rap HD", "$B/18090/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Concerts HD", "$B/18091/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Retro HD", "$B/18092/index.m3u8", "RU", "Росія"),
        MusicTvChannel("FRESH Lyrics HD", "$B/18093/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Tviksel Музыка 1 HD", "$B/18077/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Tviksel Музыка 2 HD", "$B/18079/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Tviksel Музыка 1 Int", "$B/18078/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Tviksel Музыка 2 Int", "$B/18080/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Tviksel Музыка Кино HD", "$B/18081/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Tviksel Музыка Кино Int", "$B/18082/index.m3u8", "INT", "Міжнародні"),
        MusicTvChannel("Tviksel Балет Опера HD", "$B/18083/index.m3u8", "RU", "Росія"),
        MusicTvChannel("BOX Music 4K HDR", "$B/19282/index.m3u8", "RU", "Росія"),
        MusicTvChannel("BOX Relax 4K", "$B/19283/index.m3u8", "RU", "Росія"),
        MusicTvChannel("BOX RU.RAP HD", "$B/20171/index.m3u8", "RU", "Росія"),
        MusicTvChannel("BOX Metall HD", "$B/31651/index.m3u8", "RU", "Росія"),
        MusicTvChannel("CHD-TV Rock HD", "$B/19394/index.m3u8", "RU", "Росія"),
        MusicTvChannel("NM Television HD", "$B/20161/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Plan_B HD", "$B/19249/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VeleS Dj Set", "$B/31639/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VeleS Магнитофон", "$B/31645/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Liberty Мюзикл 4K", "$B/31662/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Michael Jackson", "$B/9053/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Modern Talking", "$B/14004/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Britney Spears", "$B/14005/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Music", "$B/15516/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Rock", "$B/15517/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Metal", "$B/17033/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Rap", "$B/17034/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Хит-парад", "$B/17036/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Русский рок", "$B/17037/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Музыка", "$B/15512/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Король и Шут", "$B/31555/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Легенды Ретро ФМ", "$B/10067/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Музсоюз", "$B/15521/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Шансон", "$B/15519/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Караоке", "$B/15518/index.m3u8", "RU", "Росія"),
        MusicTvChannel("VF Музыкальный Новый год", "$B/16140/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Радио Шансон HD", "$B/16036/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Радио Хит HD", "$B/17048/index.m3u8", "RU", "Росія"),
        MusicTvChannel("Maidan", "$B/32215/index.m3u8", "RU", "Росія"),
    )

    val countries: List<Pair<String, String>>
        get() = all.map { it.country to it.countryLabel }.distinctBy { it.first }
            .sortedWith(compareBy({ if (it.first == "UA") 0 else if (it.first == "INT") 1 else 2 }, { it.second }))

    fun byCountry(code: String): List<MusicTvChannel> =
        all.filter { it.country == code }
}
